<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Categories extends \Entities\Categories implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setCategoryGroupId($categoryGroupId)
    {
        $this->__load();
        return parent::setCategoryGroupId($categoryGroupId);
    }

    public function getCategoryGroupId()
    {
        $this->__load();
        return parent::getCategoryGroupId();
    }

    public function setParentId($parentId)
    {
        $this->__load();
        return parent::setParentId($parentId);
    }

    public function getParentId()
    {
        $this->__load();
        return parent::getParentId();
    }

    public function setTitle($title)
    {
        $this->__load();
        return parent::setTitle($title);
    }

    public function getTitle()
    {
        $this->__load();
        return parent::getTitle();
    }

    public function setUrlTitle($urlTitle)
    {
        $this->__load();
        return parent::setUrlTitle($urlTitle);
    }

    public function getUrlTitle()
    {
        $this->__load();
        return parent::getUrlTitle();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setTagId($tagId)
    {
        $this->__load();
        return parent::setTagId($tagId);
    }

    public function getTagId()
    {
        $this->__load();
        return parent::getTagId();
    }

    public function setClass($class)
    {
        $this->__load();
        return parent::setClass($class);
    }

    public function getClass()
    {
        $this->__load();
        return parent::getClass();
    }

    public function setTarget($target)
    {
        $this->__load();
        return parent::setTarget($target);
    }

    public function getTarget()
    {
        $this->__load();
        return parent::getTarget();
    }

    public function setSubcategoriesVisibility($subcategoriesVisibility)
    {
        $this->__load();
        return parent::setSubcategoriesVisibility($subcategoriesVisibility);
    }

    public function getSubcategoriesVisibility()
    {
        $this->__load();
        return parent::getSubcategoriesVisibility();
    }

    public function setHide($hide)
    {
        $this->__load();
        return parent::setHide($hide);
    }

    public function getHide()
    {
        $this->__load();
        return parent::getHide();
    }

    public function setSort($sort)
    {
        $this->__load();
        return parent::setSort($sort);
    }

    public function getSort()
    {
        $this->__load();
        return parent::getSort();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'categoryGroupId', 'parentId', 'title', 'urlTitle', 'description', 'tagId', 'class', 'target', 'subcategoriesVisibility', 'hide', 'sort');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}