<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class GmaFinancialAdvisor extends \Entities\GmaFinancialAdvisor implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getAdvisorDetailsId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["advisorDetailsId"];
        }
        $this->__load();
        return parent::getAdvisorDetailsId();
    }

    public function setFinancialAdvisorName($financialAdvisorName)
    {
        $this->__load();
        return parent::setFinancialAdvisorName($financialAdvisorName);
    }

    public function getFinancialAdvisorName()
    {
        $this->__load();
        return parent::getFinancialAdvisorName();
    }

    public function setFirmName($firmName)
    {
        $this->__load();
        return parent::setFirmName($firmName);
    }

    public function getFirmName()
    {
        $this->__load();
        return parent::getFirmName();
    }

    public function setFinancialAdvisorCrdno($financialAdvisorCrdno)
    {
        $this->__load();
        return parent::setFinancialAdvisorCrdno($financialAdvisorCrdno);
    }

    public function getFinancialAdvisorCrdno()
    {
        $this->__load();
        return parent::getFinancialAdvisorCrdno();
    }

    public function setFinancialAdvisorEmailid($financialAdvisorEmailid)
    {
        $this->__load();
        return parent::setFinancialAdvisorEmailid($financialAdvisorEmailid);
    }

    public function getFinancialAdvisorEmailid()
    {
        $this->__load();
        return parent::getFinancialAdvisorEmailid();
    }

    public function setFinancialAdvisorCity($financialAdvisorCity)
    {
        $this->__load();
        return parent::setFinancialAdvisorCity($financialAdvisorCity);
    }

    public function getFinancialAdvisorCity()
    {
        $this->__load();
        return parent::getFinancialAdvisorCity();
    }

    public function setFinancialAdvisorState($financialAdvisorState)
    {
        $this->__load();
        return parent::setFinancialAdvisorState($financialAdvisorState);
    }

    public function getFinancialAdvisorState()
    {
        $this->__load();
        return parent::getFinancialAdvisorState();
    }

    public function setPortfolioId($portfolioId)
    {
        $this->__load();
        return parent::setPortfolioId($portfolioId);
    }

    public function getPortfolioId()
    {
        $this->__load();
        return parent::getPortfolioId();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'advisorDetailsId', 'financialAdvisorName', 'firmName', 'financialAdvisorCrdno', 'financialAdvisorEmailid', 'financialAdvisorCity', 'financialAdvisorState', 'portfolioId');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}