<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class GmaTransactionYodlee extends \Entities\GmaTransactionYodlee implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getYodleeTransactionId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["yodleeTransactionId"];
        }
        $this->__load();
        return parent::getYodleeTransactionId();
    }

    public function setAccountName($accountName)
    {
        $this->__load();
        return parent::setAccountName($accountName);
    }

    public function getAccountName()
    {
        $this->__load();
        return parent::getAccountName();
    }

    public function setAmount($amount)
    {
        $this->__load();
        return parent::setAmount($amount);
    }

    public function getAmount()
    {
        $this->__load();
        return parent::getAmount();
    }

    public function setCurrencyCode($currencyCode)
    {
        $this->__load();
        return parent::setCurrencyCode($currencyCode);
    }

    public function getCurrencyCode()
    {
        $this->__load();
        return parent::getCurrencyCode();
    }

    public function setCurrencyId($currencyId)
    {
        $this->__load();
        return parent::setCurrencyId($currencyId);
    }

    public function getCurrencyId()
    {
        $this->__load();
        return parent::getCurrencyId();
    }

    public function setCategory($category)
    {
        $this->__load();
        return parent::setCategory($category);
    }

    public function getCategory()
    {
        $this->__load();
        return parent::getCategory();
    }

    public function setCategoryId($categoryId)
    {
        $this->__load();
        return parent::setCategoryId($categoryId);
    }

    public function getCategoryId()
    {
        $this->__load();
        return parent::getCategoryId();
    }

    public function setCategoryTypeId($categoryTypeId)
    {
        $this->__load();
        return parent::setCategoryTypeId($categoryTypeId);
    }

    public function getCategoryTypeId()
    {
        $this->__load();
        return parent::getCategoryTypeId();
    }

    public function setContainer($container)
    {
        $this->__load();
        return parent::setContainer($container);
    }

    public function getContainer()
    {
        $this->__load();
        return parent::getContainer();
    }

    public function setItemAccountId($itemAccountId)
    {
        $this->__load();
        return parent::setItemAccountId($itemAccountId);
    }

    public function getItemAccountId()
    {
        $this->__load();
        return parent::getItemAccountId();
    }

    public function setTxnBaseType($txnBaseType)
    {
        $this->__load();
        return parent::setTxnBaseType($txnBaseType);
    }

    public function getTxnBaseType()
    {
        $this->__load();
        return parent::getTxnBaseType();
    }

    public function setBusinessExpense($businessExpense)
    {
        $this->__load();
        return parent::setBusinessExpense($businessExpense);
    }

    public function getBusinessExpense()
    {
        $this->__load();
        return parent::getBusinessExpense();
    }

    public function setMedicalExpense($medicalExpense)
    {
        $this->__load();
        return parent::setMedicalExpense($medicalExpense);
    }

    public function getMedicalExpense()
    {
        $this->__load();
        return parent::getMedicalExpense();
    }

    public function setMemo($memo)
    {
        $this->__load();
        return parent::setMemo($memo);
    }

    public function getMemo()
    {
        $this->__load();
        return parent::getMemo();
    }

    public function setReimbursable($reimbursable)
    {
        $this->__load();
        return parent::setReimbursable($reimbursable);
    }

    public function getReimbursable()
    {
        $this->__load();
        return parent::getReimbursable();
    }

    public function setTxtSimpleDescription($txtSimpleDescription)
    {
        $this->__load();
        return parent::setTxtSimpleDescription($txtSimpleDescription);
    }

    public function getTxtSimpleDescription()
    {
        $this->__load();
        return parent::getTxtSimpleDescription();
    }

    public function setSharedTxn($sharedTxn)
    {
        $this->__load();
        return parent::setSharedTxn($sharedTxn);
    }

    public function getSharedTxn()
    {
        $this->__load();
        return parent::getSharedTxn();
    }

    public function setTaxDeductible($taxDeductible)
    {
        $this->__load();
        return parent::setTaxDeductible($taxDeductible);
    }

    public function getTaxDeductible()
    {
        $this->__load();
        return parent::getTaxDeductible();
    }

    public function setTxnId($txnId)
    {
        $this->__load();
        return parent::setTxnId($txnId);
    }

    public function getTxnId()
    {
        $this->__load();
        return parent::getTxnId();
    }

    public function setTxnStatus($txnStatus)
    {
        $this->__load();
        return parent::setTxnStatus($txnStatus);
    }

    public function getTxnStatus()
    {
        $this->__load();
        return parent::getTxnStatus();
    }

    public function setCreatedDate($createdDate)
    {
        $this->__load();
        return parent::setCreatedDate($createdDate);
    }

    public function getCreatedDate()
    {
        $this->__load();
        return parent::getCreatedDate();
    }

    public function setPortfolioId($portfolioId)
    {
        $this->__load();
        return parent::setPortfolioId($portfolioId);
    }

    public function getPortfolioId()
    {
        $this->__load();
        return parent::getPortfolioId();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'yodleeTransactionId', 'accountName', 'amount', 'currencyCode', 'currencyId', 'category', 'categoryId', 'categoryTypeId', 'container', 'itemAccountId', 'txnBaseType', 'businessExpense', 'medicalExpense', 'memo', 'reimbursable', 'txtSimpleDescription', 'sharedTxn', 'taxDeductible', 'txnId', 'txnStatus', 'createdDate', 'portfolioId');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}