<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class GmaPortfolio extends \Entities\GmaPortfolio implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getPortfolioId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["portfolioId"];
        }
        $this->__load();
        return parent::getPortfolioId();
    }

    public function setPortfolioName($portfolioName)
    {
        $this->__load();
        return parent::setPortfolioName($portfolioName);
    }

    public function getPortfolioName()
    {
        $this->__load();
        return parent::getPortfolioName();
    }

    public function setAdvisorDetailsId($advisorDetailsId)
    {
        $this->__load();
        return parent::setAdvisorDetailsId($advisorDetailsId);
    }

    public function getAdvisorDetailsId()
    {
        $this->__load();
        return parent::getAdvisorDetailsId();
    }

    public function setCreatedDate($createdDate)
    {
        $this->__load();
        return parent::setCreatedDate($createdDate);
    }

    public function getCreatedDate()
    {
        $this->__load();
        return parent::getCreatedDate();
    }

    public function setDefaultAsset($defaultAsset)
    {
        $this->__load();
        return parent::setDefaultAsset($defaultAsset);
    }

    public function getDefaultAsset()
    {
        $this->__load();
        return parent::getDefaultAsset();
    }

    public function setPortfolioTypeId($portfolioTypeId)
    {
        $this->__load();
        return parent::setPortfolioTypeId($portfolioTypeId);
    }

    public function getPortfolioTypeId()
    {
        $this->__load();
        return parent::getPortfolioTypeId();
    }

    public function setUserDefineAsset($userDefineAsset)
    {
        $this->__load();
        return parent::setUserDefineAsset($userDefineAsset);
    }

    public function getUserDefineAsset()
    {
        $this->__load();
        return parent::getUserDefineAsset();
    }

    public function setUser(\Entities\GmaUser $user = NULL)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'portfolioId', 'portfolioName', 'advisorDetailsId', 'createdDate', 'defaultAsset', 'portfolioTypeId', 'userDefineAsset', 'user');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}