<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Galleries extends \Entities\Galleries implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setTitle($title)
    {
        $this->__load();
        return parent::setTitle($title);
    }

    public function getTitle()
    {
        $this->__load();
        return parent::getTitle();
    }

    public function setResize($resize)
    {
        $this->__load();
        return parent::setResize($resize);
    }

    public function getResize()
    {
        $this->__load();
        return parent::getResize();
    }

    public function setImageWidth($imageWidth)
    {
        $this->__load();
        return parent::setImageWidth($imageWidth);
    }

    public function getImageWidth()
    {
        $this->__load();
        return parent::getImageWidth();
    }

    public function setImageHeight($imageHeight)
    {
        $this->__load();
        return parent::setImageHeight($imageHeight);
    }

    public function getImageHeight()
    {
        $this->__load();
        return parent::getImageHeight();
    }

    public function setImageCrop($imageCrop)
    {
        $this->__load();
        return parent::setImageCrop($imageCrop);
    }

    public function getImageCrop()
    {
        $this->__load();
        return parent::getImageCrop();
    }

    public function setThumbs($thumbs)
    {
        $this->__load();
        return parent::setThumbs($thumbs);
    }

    public function getThumbs()
    {
        $this->__load();
        return parent::getThumbs();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'title', 'resize', 'imageWidth', 'imageHeight', 'imageCrop', 'thumbs');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}