<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class GmaAssetAllocationDetails extends \Entities\GmaAssetAllocationDetails implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getAssetAllocationDetailId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["assetAllocationDetailId"];
        }
        $this->__load();
        return parent::getAssetAllocationDetailId();
    }

    public function setAssetPercentage($assetPercentage)
    {
        $this->__load();
        return parent::setAssetPercentage($assetPercentage);
    }

    public function getAssetPercentage()
    {
        $this->__load();
        return parent::getAssetPercentage();
    }

    public function setClassId($classId)
    {
        $this->__load();
        return parent::setClassId($classId);
    }

    public function getClassId()
    {
        $this->__load();
        return parent::getClassId();
    }

    public function setAssetAllocation(\Entities\GmaAssetAllocation $assetAllocation = NULL)
    {
        $this->__load();
        return parent::setAssetAllocation($assetAllocation);
    }

    public function getAssetAllocation()
    {
        $this->__load();
        return parent::getAssetAllocation();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'assetAllocationDetailId', 'assetPercentage', 'classId', 'assetAllocation');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}