<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class GmaCashFlow extends \Entities\GmaCashFlow implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getCashFlowId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["cashFlowId"];
        }
        $this->__load();
        return parent::getCashFlowId();
    }

    public function setCashFlowDate($cashFlowDate)
    {
        $this->__load();
        return parent::setCashFlowDate($cashFlowDate);
    }

    public function getCashFlowDate()
    {
        $this->__load();
        return parent::getCashFlowDate();
    }

    public function setCashFlowType($cashFlowType)
    {
        $this->__load();
        return parent::setCashFlowType($cashFlowType);
    }

    public function getCashFlowType()
    {
        $this->__load();
        return parent::getCashFlowType();
    }

    public function setAmount($amount)
    {
        $this->__load();
        return parent::setAmount($amount);
    }

    public function getAmount()
    {
        $this->__load();
        return parent::getAmount();
    }

    public function setPortfolioId($portfolioId)
    {
        $this->__load();
        return parent::setPortfolioId($portfolioId);
    }

    public function getPortfolioId()
    {
        $this->__load();
        return parent::getPortfolioId();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'cashFlowId', 'cashFlowDate', 'cashFlowType', 'amount', 'portfolioId');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}